### ISSUE TITLE
Suggestion - Add MacOS version compatibility description into README

### ISSUE THREAD

**Issue by spiritually-soup** [Jerry23011/VirusTotal-macOS#6]
Hi, tried downloading the latest release dmg + also tried installing via Homebrew, but am running into issues saying my OS is not compatible and/or that I need MacOS Sonoma.

I'm currently on Ventura - is there any particular release that should be compatible?

Would suggest adding this info into the README to make things clearer!

**Comment by Jerry23011** [comment]
So sorry to hear that, but there are a few APIs in the project that are macOS 14+. The good news is I will consider leaving the minimum system support as macOS 14 for years to come, so you'll be able to catch up when you update to that version!

The [Download](https://github.com/Jerry23011/VirusTotal-macOS?tab=readme-ov-file#downloads) section in the README indicates this is macOS 14.0 compatible with a badge.
